import { object_to_array } from "./resource";

export const DoT_ID = [
    {
        actionid: '722E',
        action_potential: 20000,
        dotid: '07F6',
        name: 'テンパランス：効果',
        potential: 4000,
        max: 5,
        type: 'HoT'
    }, {
        actionid: '',//ソルトアース起動71A6
        action_potential: 0,
        dotid: '0BDD',
        name: 'ソルトアース',
        potential: 6000,
        max: 5,
        type: 'HoT'
    }, {
        actionid: '',//ソルトアース起動71A6
        action_potential: 0,
        dotid: '0BDE',
        name: 'ソルトアース[害]',
        potential: 6000,
        max: 5,
        type: 'DoT'
    }, {
        actionid: '7231',
        action_potential: 0,
        dotid: '0C11',
        name: '蟲毒法',
        potential: 3000,
        max: 12,
        type: 'DoT'
    }, {
        actionid: '7232',//展開戦術
        action_potential: 0,
        dotid: '0C11',
        name: '蟲毒法',
        potential: 3000,
        max: 12,
        type: 'DoT'
    }, {
        actionid: '723B',
        action_potential: 0,//6000-9000 HP可変
        dotid: '0C1B',
        name: 'アスペクトベネフィク[日]',
        potential: 3000,
        max: 15,
        type: 'HoT'
    }, {
        actionid: '7249',
        action_potential: 0,
        dotid: '0C24',
        name: 'エウクラシア・ドシスIII',
        potential: 3000,
        max: 12,
        type: 'DoT'
    }, {
        actionid: '7252',
        action_potential: 0,
        dotid: '0C30',
        name: 'リュペー',
        potential: 8000,
        max: 5,
        type: 'DoT'
    }, {
        actionid: '72DE',
        action_potential: 4000,
        dotid: '07E3',
        name: 'バイオブラスト',
        potential: 4000,
        max: 12,
        type: 'DoT'
    }, {//black mage
        actionid: 'A208',
        action_potential: 16000,//3000-6000-9000可変
        dotid: '0C92',
        name: '火傷',
        potential: 4000,
        max: 6,
        type: 'DoT'
    }, {
        actionid: '73E5',
        action_potential: 9000,
        dotid: '0C9B',
        name: 'スリップストリーム[害]',
        potential: 4500,
        max: 6,
        type: 'DoT'
    }, {
        actionid: '73F0',//フェニックスが使用
        action_potential: 0,
        dotid: '0C9E',
        name: '不死鳥の翼',
        potential: 4000,
        max: 15,
        type: 'HoT'
    }, {
        actionid: '73F1',
        action_potential: 4000,
        dotid: '0C9F',
        name: '火焔',
        potential: 4000,
        max: 6,
        type: 'DoT'
    }, {
        actionid: 'A213',
        action_potential: 8000,
        dotid: '10DF',
        name: 'スコーチ',
        potential: 4000,
        max: 6,
        type: 'DoT'
    }, {
        actionid: '7340',
        action_potential: 4000,
        dotid: '0C70',
        name: '劫火滅却の術',
        potential: 4000,
        max: 12,
        type: 'DoT'
    }, {
        actionid: '7344',
        action_potential: 8000,
        dotid: '0C75',
        name: '命水',
        potential: 4000,
        max: 12,
        type: 'HoT'
    }, {
        actionid: '',//ドトン発動734A
        action_potential: 0,
        dotid: '0C07',
        name: '土遁の術[害]',
        potential: 3000,
        max: 5,
        type: 'DoT'
    }, {
        actionid: '',
        //守護のクレスト　B2D
        //活性のクレスト　 B2E
        action_potential: 0,
        dotid: '0B2E',
        name: '活性のクレスト',
        potential: 6000,
        max: 6,
        type: 'HoT'
    }, {
        actionid: '9931',
        action_potential: 8000,
        dotid: '1017',
        name: 'スタープリズム',
        potential: 2000,
        max: 15,
        type: 'HoT'
    }, {
        actionid: '9928',
        action_potential: 8000,
        dotid: '1010',
        name: 'イマジンファング',
        potential: 4000,
        max: 12,
        type: 'DoT'
    }, {
        actionid: '26FA',
        action_potential: 40000,
        dotid: '010B',
        name: '火傷',
        potential: 10000,
        max: 12,
        type: 'DoT'
    }, {
        actionid: '',
        dotid: '0597',
        name: 'タワーフィールド',
        potential: 4000,
        max: 1200,
        type: 'HoT'
    }, {// not use?
        actionid: '',
        dotid: '0598',
        name: 'タワーフィールド',
        potential: 4000,
        max: 1200,
        type: 'HoT'
    }, {
        actionid: '',//RedSans
        dotid: '0EA8',
        name: '憩いの水',
        potential: 5000,
        max: 30,
        type: 'HoT'
    }, {
        actionid: '',//RedSans
        dotid: '0EA9',
        name: '憩いの水',
        potential: 7500,
        max: 9999,
        type: 'HoT'
    }, {
        actionid: '',//The Border land Ruins
        dotid: '0C01',
        name: '感電',
        potential: 10000,//Wakaran
        max: 9999,
        type: 'DoT'
    }
];

export const Unique_DoT = [{
    id: 'A2C',
    name: 'カルディア',
    type: 'HoT'
}, {
    id: '51A',
    name: 'ソウルサバイバー',
    type: 'DoT'
}, {
    id: 'C64',
    name: '急所系穴',
    type: 'DoT'
}, {
    id: 'C27',
    name: 'ハイマの印',
    type: 'HoT'
}, {
    id: 'C9E',
    name: '不死鳥の翼',
    type: 'HoT'
}, {
    id: 'C20',
    name: 'マクロコスモス',
    type: 'HoT'
}, {
    id: 'C67',
    name: 'メテオドライブ',
    type: 'DoT'
}, {
    id: '10C8',
    name: '????',
    type: 'HoT'
}];

export const DoT_ID_Array = object_to_array(DoT_ID, 'dotid');

export const Unique_DoT_ID_Array = object_to_array(Unique_DoT, 'id');