import './css/header.css'

import { useState } from 'react';
import { time_change } from './v4/timer/timer_format.js';
import { sample_encounter_data } from './OverlayMain';

import {sample_crystal_data_calc} from './v4/sample/workSample.js'
import { rootRender } from '.';
import { EncounterState } from './OverlayMain';
var LCS_HEADER_HIDE = false;

export const HeaderSimple = (EncounterData) => {
    const [hide, setActive] = useState(LCS_HEADER_HIDE);

    const hide_toggle = () => {
        setActive(!hide)
    }
    return (
        <div>
            {hide?'' :<HeaderDetail EncounterData={EncounterData}/> }
            <div className='headerOpen' onClick={hide_toggle}>
                {hide?<div className='roundButton' ></div>:''}
                <div className='horizontalLine flex-center' style={{backgroundColor:'gray'}}></div>
            </div>
        </div>
    );
}

const HeaderDetail = (EncounterData) => {
    
    let Encounter =EncounterData.EncounterData.EncounterData;
    if(Object.keys(EncounterData).length === 0){
        Encounter = {CurrentZoneName:'Unknown Zone',DURATION:'0'};
    }
    let time = time_change(Number(Encounter.DURATION));
    return (
        <header>
            <div className='header-Top'>
                <div className='flex-center'>
                    <span className='icon-app_fc' onClick={testmoduleStart}></span>
                    <span id='zoneName'>{Encounter.CurrentZoneName}</span>
                </div>
                <div className='flex-center'>
                    <span className='bebasText flex-center'>
                        <span className='icon-ScheduleTime spaceExLow'></span>
                        <span id='BattleTime_min'>{time[0]}</span>
                        <span id='BattleTime_dot'>:</span>
                        <span id='BattleTime_sec'>{time[1]}</span>
                    </span>
                    <span className='icon-app_drawer_setting spaceExLow' onClick={() => { console.log("SettingButton") }}></span>
                </div>
            </div>
        </header>
    );
}

function testmoduleStart() {
    let data = sample_encounter_data2();
data.Combatant['YOU'].encdps = '1245.32';
//delete data.Combatant['Oppresor Tanaka'];
    //sample_crystal_data_calc(2);
    console.log(data);
    window.EncounterState(data);
}


//test combatant data
export function sample_encounter_data2() {
    let json = {
      "type": "CombatData",
      "Encounter": {
        "n": "\n",
        "t": "\t",
        "title": "サウス・ファルコンタワー",
        "duration": "14:34",
        "DURATION": "874",
        "damage": "6764581",
        "damage-m": "6.76",
        "damage-*": "6.76M",
        "DAMAGE-k": "6765",
        "DAMAGE-m": "7",
        "DAMAGE-b": "0",
        "DAMAGE-*": "6764K",
        "dps": "7739.80",
        "dps-*": "dps-*",
        "DPS": "7740",
        "DPS-k": "8",
        "DPS-m": "DPS-m",
        "DPS-*": "7739",
        "encdps": "7739.80",
        "encdps-*": "7.74K",
        "ENCDPS": "7740",
        "ENCDPS-k": "8",
        "ENCDPS-m": "0",
        "ENCDPS-*": "7739",
        "hits": "2369",
        "crithits": "0",
        "crithit%": Math.floor(Math.random() * 51) + '%',
        "misses": "6",
        "hitfailed": "46",
        "swings": "2421",
        "tohit": "94.34",
        "TOHIT": "94",
        "maxhit": "レイヴン・オプレッサー (Michael Twining)-大爆発-253146",
        "MAXHIT": "レイヴン・オプレッサー (Michael Twining)-253146",
        "maxhit-*": "レイヴン・オプレッサー (Michael Twining)-大爆発-253.15K",
        "MAXHIT-*": "レイヴン・オプレッサー (Michael Twining)-253K",
        "healed": "1836435",
        "enchps": "2101.18",
        "enchps-*": "2.10K",
        "ENCHPS": "2101",
        "ENCHPS-k": "2",
        "ENCHPS-m": "0",
        "ENCHPS-*": "2101",
        "heals": "426",
        "critheals": "0",
        "critheal%": Math.floor(Math.random() * 51) + '%',
        "cures": "0",
        "maxheal": "Oppresor Tanaka-Unknown-8517",
        "MAXHEAL": "Oppresor Tanaka-8517",
        "maxhealward": "Oppresor Tanaka-Unknown-8517",
        "MAXHEALWARD": "Oppresor Tanaka-8517",
        "maxheal-*": "Oppresor Tanaka-Unknown-8.52K",
        "MAXHEAL-*": "Oppresor Tanaka-8517",
        "maxhealward-*": "Oppresor Tanaka-Unknown-8.52K",
        "MAXHEALWARD-*": "Oppresor Tanaka-8517",
        "damagetaken": "3275872",
        "damagetaken-*": "3.28M",
        "healstaken": "2194879",
        "healstaken-*": "2.19M",
        "powerdrain": "0",
        "powerdrain-*": "0",
        "powerheal": "160000",
        "powerheal-*": "160.00K",
        "kills": "120",
        "deaths": "39",
        "CurrentZoneName": "Hidden Gorge",
        "Last10DPS": "5609",
        "Last30DPS": "5368",
        "Last60DPS": "7686"
      },
      "Combatant": {
        "YOU": {
          "n": "\n",
          "t": "\t",
          "name": 'YOU',
          "duration": "14:34",
          "DURATION": "874",
          "damage": "635770",
          "damage-m": "0.64",
          "damage-b": "0.00",
          "damage-*": "635.77K",
          "DAMAGE-k": "636",
          "DAMAGE-m": "1",
          "DAMAGE-b": "0",
          "DAMAGE-*": "635K",
          "damage%": "9%",
          "dps": "727.43",
          "dps-*": "727",
          "DPS": "727",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "727",
          "encdps": "727.43",
          "encdps-*": "727",
          "ENCDPS": "727",
          "ENCDPS-k": "1",
          "ENCDPS-m": "0",
          "ENCDPS-*": "727",
          "hits": "289",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "10",
          "swings": "299",
          "tohit": "96.66",
          "TOHIT": "97",
          "maxhit": "ゼノグロシー-5617",
          "MAXHIT": "5617",
          "maxhit-*": "ゼノグロシー-5.62K",
          "MAXHIT-*": "5617",
          "healed": "245137",
          "healed%": "13%",
          "enchps": "280.48",
          "enchps-*": "11280",
          "ENCHPS": "280",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "280",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "53",
          "cures": "0",
          "maxheal": "Unknown-7053",
          "MAXHEAL": "7053",
          "maxhealward": "Unknown-7053",
          "MAXHEALWARD": "7053",
          "maxheal-*": "Unknown-7.05K",
          "MAXHEAL-*": "7.05K",
          "maxhealward-*": "Unknown-7.05K",
          "MAXHEALWARD-*": "7.05K",
          "damagetaken": "181960",
          "damagetaken-*": "181.96K",
          "healstaken": "297308",
          "healstaken-*": "297.31K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "140000",
          "powerheal-*": "140.00K",
          "kills": "18",
          "deaths": "2",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "40",
          "Last60DPS": "345",
          "Job": "Rpr",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "90.57",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "245137"
        },
        "Chaiser Satou": {
          "n": "\n",
          "t": "\t",
          "name": "Chaiser Satou",
          "duration": "14:33",
          "DURATION": "873",
          "damage": "556783",
          "damage-m": "0.56",
          "damage-b": "0.00",
          "damage-*": "556.78K",
          "DAMAGE-k": "557",
          "DAMAGE-m": "1",
          "DAMAGE-b": "0",
          "DAMAGE-*": "556K",
          "damage%": "8%",
          "dps": "637.78",
          "dps-*": "637",
          "DPS": "638",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "637",
          "encdps": "637.05",
          "encdps-*": "637",
          "ENCDPS": "637",
          "ENCDPS-k": "1",
          "ENCDPS-m": "0",
          "ENCDPS-*": "637",
          "hits": "426",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "5",
          "hitfailed": "0",
          "swings": "431",
          "tohit": "98.84",
          "TOHIT": "99",
          "maxhit": "ドリル-3277",
          "MAXHIT": "3277",
          "maxhit-*": "ドリル-3.28K",
          "MAXHIT-*": "3277",
          "healed": "207863",
          "healed%": "11%",
          "enchps": "237.83",
          "enchps-*": "237",
          "ENCHPS": "238",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "237",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "47",
          "cures": "0",
          "maxheal": "Unknown-8500",
          "MAXHEAL": "8500",
          "maxhealward": "Unknown-8500",
          "MAXHEALWARD": "8500",
          "maxheal-*": "Unknown-8.50K",
          "MAXHEAL-*": "8.50K",
          "maxhealward-*": "Unknown-8.50K",
          "MAXHEALWARD-*": "8.50K",
          "damagetaken": "169694",
          "damagetaken-*": "169.69K",
          "healstaken": "269176",
          "healstaken-*": "269.18K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "17",
          "deaths": "2",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "54",
          "Last60DPS": "242",
          "Job": "Mch",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "207863"
        },
        "Oppresor Tanaka": {
          "n": "\n",
          "t": "\t",
          "name": "Oppresor Tanaka",
          "duration": "14:36",
          "DURATION": "876",
          "damage": "615056",
          "damage-m": "0.62",
          "damage-b": "0.00",
          "damage-*": "615.06K",
          "DAMAGE-k": "615",
          "DAMAGE-m": "1",
          "DAMAGE-b": "0",
          "DAMAGE-*": "615K",
          "damage%": "9%",
          "dps": "702.12",
          "dps-*": "702",
          "DPS": "702",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "702",
          "encdps": "703.73",
          "encdps-*": "703",
          "ENCDPS": "704",
          "ENCDPS-k": "1",
          "ENCDPS-m": "0",
          "ENCDPS-*": "703",
          "hits": "395",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "1",
          "hitfailed": "4",
          "swings": "400",
          "tohit": "98.75",
          "TOHIT": "99",
          "maxhit": "ドリル-3618",
          "MAXHIT": "3618",
          "maxhit-*": "ドリル-3.62K",
          "MAXHIT-*": "3618",
          "healed": "250370",
          "healed%": "13%",
          "enchps": "286.46",
          "enchps-*": "286",
          "ENCHPS": "286",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "286",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "49",
          "cures": "0",
          "maxheal": "Unknown-8517",
          "MAXHEAL": "8517",
          "maxhealward": "Unknown-8517",
          "MAXHEALWARD": "8517",
          "maxheal-*": "Unknown-8.52K",
          "MAXHEAL-*": "8.52K",
          "maxhealward-*": "Unknown-8.52K",
          "MAXHEALWARD-*": "8.52K",
          "damagetaken": "232437",
          "damagetaken-*": "232.44K",
          "healstaken": "314711",
          "healstaken-*": "314.71K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "18",
          "deaths": "2",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "51",
          "Last60DPS": "428",
          "Job": "Sge",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "97.08",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "250370"
        },
        "Samuel Takano": {
          "n": "\n",
          "t": "\t",
          "name": "Samuel Takano",
          "duration": "12:48",
          "DURATION": "768",
          "damage": "467153",
          "damage-m": "0.47",
          "damage-b": "0.00",
          "damage-*": "467.15K",
          "DAMAGE-k": "467",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "467K",
          "damage%": "6%",
          "dps": "608.27",
          "dps-*": "608",
          "DPS": "608",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "608",
          "encdps": "534.50",
          "encdps-*": "534",
          "ENCDPS": "535",
          "ENCDPS-k": "1",
          "ENCDPS-m": "0",
          "ENCDPS-*": "534",
          "hits": "68",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "68",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "レーザーエックススウォード-13686",
          "MAXHIT": "13686",
          "maxhit-*": "レーザーエックススウォード-13.69K",
          "MAXHIT-*": "13K",
          "healed": "54514",
          "healed%": "2%",
          "enchps": "62.37",
          "enchps-*": "62",
          "ENCHPS": "62",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "62",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "11",
          "cures": "0",
          "maxheal": "Unknown-7406",
          "MAXHEAL": "7406",
          "maxhealward": "Unknown-7406",
          "MAXHEALWARD": "7406",
          "maxheal-*": "Unknown-7.41K",
          "MAXHEAL-*": "7.41K",
          "maxhealward-*": "Unknown-7.41K",
          "MAXHEALWARD-*": "7.41K",
          "damagetaken": "248122",
          "damagetaken-*": "248.12K",
          "healstaken": "55716",
          "healstaken-*": "55.72K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "9",
          "deaths": "4",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "War",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "54514"
        },
        "Gabriel Tepes": {
          "n": "\n",
          "t": "\t",
          "name": "Gabriel Tepes",
          "duration": "14:02",
          "DURATION": "842",
          "damage": "397698",
          "damage-m": "0.40",
          "damage-b": "0.00",
          "damage-*": "397.70K",
          "DAMAGE-k": "398",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "397K",
          "damage%": "5%",
          "dps": "472.33",
          "dps-*": "472",
          "DPS": "472",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "472",
          "encdps": "455.03",
          "encdps-*": "455",
          "ENCDPS": "455",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "455",
          "hits": "240",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "240",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "レーザーエックススウォード-12763",
          "MAXHIT": "12763",
          "maxhit-*": "レーザーエックススウォード-12.76K",
          "MAXHIT-*": "12K",
          "healed": "235187",
          "healed%": "12%",
          "enchps": "269.09",
          "enchps-*": "269",
          "ENCHPS": "269",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "269",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "48",
          "cures": "0",
          "maxheal": "Unknown-8081",
          "MAXHEAL": "8081",
          "maxhealward": "Unknown-8081",
          "MAXHEALWARD": "8081",
          "maxheal-*": "Unknown-8.08K",
          "MAXHEAL-*": "8.08K",
          "maxhealward-*": "Unknown-8.08K",
          "MAXHEALWARD-*": "8.08K",
          "damagetaken": "257524",
          "damagetaken-*": "257.52K",
          "healstaken": "274462",
          "healstaken-*": "274.46K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "8",
          "deaths": "4",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "123",
          "Job": "Dnc",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "235187"
        },
        "Daniel Tepesh": {
          "n": "\n",
          "t": "\t",
          "name": "Daniel Tepesh",
          "duration": "14:31",
          "DURATION": "871",
          "damage": "546235",
          "damage-m": "0.55",
          "damage-b": "0.00",
          "damage-*": "546.24K",
          "DAMAGE-k": "546",
          "DAMAGE-m": "1",
          "DAMAGE-b": "0",
          "DAMAGE-*": "546K",
          "damage%": "8%",
          "dps": "627.14",
          "dps-*": "627",
          "DPS": "627",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "627",
          "encdps": "624.98",
          "encdps-*": "624",
          "ENCDPS": "625",
          "ENCDPS-k": "1",
          "ENCDPS-m": "0",
          "ENCDPS-*": "624",
          "hits": "121",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "3",
          "swings": "124",
          "tohit": "97.58",
          "TOHIT": "98",
          "maxhit": "メガビーム-15571",
          "MAXHIT": "15571",
          "maxhit-*": "メガビーム-15.57K",
          "MAXHIT-*": "15K",
          "healed": "34414",
          "healed%": "1%",
          "enchps": "39.38",
          "enchps-*": "39",
          "ENCHPS": "39",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "39",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "12",
          "cures": "0",
          "maxheal": "Unknown-4571",
          "MAXHEAL": "4571",
          "maxhealward": "Unknown-4571",
          "MAXHEALWARD": "4571",
          "maxheal-*": "Unknown-4.57K",
          "MAXHEAL-*": "4.57K",
          "maxhealward-*": "Unknown-4.57K",
          "MAXHEALWARD-*": "4.57K",
          "damagetaken": "185116",
          "damagetaken-*": "185.12K",
          "healstaken": "63557",
          "healstaken-*": "63.56K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "10000",
          "powerheal-*": "10.00K",
          "kills": "12",
          "deaths": "1",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "717",
          "Job": "Smn",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "89.77",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "34414"
        },
        "Nathaniel Tamwood": {
          "n": "\n",
          "t": "\t",
          "name": "Nathaniel Tamwood",
          "duration": "13:46",
          "DURATION": "826",
          "damage": "287309",
          "damage-m": "0.29",
          "damage-b": "0.00",
          "damage-*": "287.31K",
          "DAMAGE-k": "287",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "287K",
          "damage%": "4%",
          "dps": "347.83",
          "dps-*": "347",
          "DPS": "348",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "347",
          "encdps": "328.73",
          "encdps-*": "328",
          "ENCDPS": "329",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "328",
          "hits": "113",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "1",
          "swings": "114",
          "tohit": "99.12",
          "TOHIT": "99",
          "maxhit": "レーザーエックススウォード-12969",
          "MAXHIT": "12969",
          "maxhit-*": "レーザーエックススウォード-12.97K",
          "MAXHIT-*": "12K",
          "healed": "222141",
          "healed%": "12%",
          "enchps": "254.17",
          "enchps-*": "254",
          "ENCHPS": "254",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "254",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "62",
          "cures": "0",
          "maxheal": "Unknown-6858",
          "MAXHEAL": "6858",
          "maxhealward": "Unknown-6858",
          "MAXHEALWARD": "6858",
          "maxheal-*": "Unknown-6.86K",
          "MAXHEAL-*": "6.86K",
          "maxhealward-*": "Unknown-6.86K",
          "MAXHEALWARD-*": "6.86K",
          "damagetaken": "345234",
          "damagetaken-*": "345.23K",
          "healstaken": "231389",
          "healstaken-*": "231.39K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "5000",
          "powerheal-*": "5.00K",
          "kills": "7",
          "deaths": "5",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Mnk",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "99.48",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "222141"
        },
        "Maxsizeno Namenoohito": {
          "n": "\n",
          "t": "\t",
          "name": "Maxsizeno Namenoohito",
          "duration": "11:54",
          "DURATION": "714",
          "damage": "126757",
          "damage-m": "0.13",
          "damage-b": "0.00",
          "damage-*": "126.76K",
          "DAMAGE-k": "127",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "126K",
          "damage%": "1%",
          "dps": "177.53",
          "dps-*": "177",
          "DPS": "178",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "177",
          "encdps": "145.03",
          "encdps-*": "145",
          "ENCDPS": "145",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "145",
          "hits": "119",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "119",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "エアアンカー-2610",
          "MAXHIT": "2610",
          "maxhit-*": "エアアンカー-2.61K",
          "MAXHIT-*": "2610",
          "healed": "100388",
          "healed%": "5%",
          "enchps": "114.86",
          "enchps-*": "114",
          "ENCHPS": "115",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "114",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "20",
          "cures": "0",
          "maxheal": "Unknown-6723",
          "MAXHEAL": "6723",
          "maxhealward": "Unknown-6723",
          "MAXHEALWARD": "6723",
          "maxheal-*": "Unknown-6.72K",
          "MAXHEAL-*": "6.72K",
          "maxhealward-*": "Unknown-6.72K",
          "MAXHEALWARD-*": "6.72K",
          "damagetaken": "267641",
          "damagetaken-*": "267.64K",
          "healstaken": "130996",
          "healstaken-*": "131.00K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "2",
          "deaths": "4",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Mch",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "100388"
        },
        "Michael Twining": {
          "n": "\n",
          "t": "\t",
          "name": "Michael Twining",
          "duration": "13:40",
          "DURATION": "820",
          "damage": "126579",
          "damage-m": "0.13",
          "damage-b": "0.00",
          "damage-*": "126.58K",
          "DAMAGE-k": "127",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "126K",
          "damage%": "1%",
          "dps": "154.36",
          "dps-*": "154",
          "DPS": "154",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "154",
          "encdps": "144.83",
          "encdps-*": "144",
          "ENCDPS": "145",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "144",
          "hits": "25",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "25",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "レーザーエックススウォード-12823",
          "MAXHIT": "12823",
          "maxhit-*": "レーザーエックススウォード-12.82K",
          "MAXHIT-*": "12K",
          "healed": "27648",
          "healed%": "1%",
          "enchps": "31.63",
          "enchps-*": "31",
          "ENCHPS": "32",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "31",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "5",
          "cures": "0",
          "maxheal": "Unknown-7982",
          "MAXHEAL": "7982",
          "maxhealward": "Unknown-7982",
          "MAXHEALWARD": "7982",
          "maxheal-*": "Unknown-7.98K",
          "MAXHEAL-*": "7.98K",
          "maxhealward-*": "Unknown-7.98K",
          "MAXHEALWARD-*": "7.98K",
          "damagetaken": "289838",
          "damagetaken-*": "289.84K",
          "healstaken": "27648",
          "healstaken-*": "27.65K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "2",
          "deaths": "3",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "178",
          "Job": "Drg",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "27648"
        },
        "Raphael Tachibana": {
          "n": "\n",
          "t": "\t",
          "name": "Raphael Tachibana",
          "duration": "12:12",
          "DURATION": "732",
          "damage": "107830",
          "damage-m": "0.11",
          "damage-b": "0.00",
          "damage-*": "107.83K",
          "DAMAGE-k": "108",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "107K",
          "damage%": "1%",
          "dps": "147.31",
          "dps-*": "147",
          "DPS": "147",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "147",
          "encdps": "123.38",
          "encdps-*": "123",
          "ENCDPS": "123",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "123",
          "hits": "76",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "1",
          "swings": "77",
          "tohit": "98.70",
          "TOHIT": "99",
          "maxhit": "スターダイバー-3436",
          "MAXHIT": "3436",
          "maxhit-*": "スターダイバー-3.44K",
          "MAXHIT-*": "3436",
          "healed": "25681",
          "healed%": "1%",
          "enchps": "29.38",
          "enchps-*": "29",
          "ENCHPS": "29",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "29",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "4",
          "cures": "0",
          "maxheal": "Unknown-7554",
          "MAXHEAL": "7554",
          "maxhealward": "Unknown-7554",
          "MAXHEALWARD": "7554",
          "maxheal-*": "Unknown-7.55K",
          "MAXHEAL-*": "7.55K",
          "maxhealward-*": "Unknown-7.55K",
          "MAXHEALWARD-*": "7.55K",
          "damagetaken": "88187",
          "damagetaken-*": "88.19K",
          "healstaken": "26657",
          "healstaken-*": "26.66K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "2",
          "deaths": "3",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Drg",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "97.67",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "25681"
        },
        "Ansel Tod": {
          "n": "\n",
          "t": "\t",
          "name": "Ansel Tod",
          "duration": "14:11",
          "DURATION": "851",
          "damage": "84652",
          "damage-m": "0.08",
          "damage-b": "0.00",
          "damage-*": "84.65K",
          "DAMAGE-k": "85",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "84K",
          "damage%": "1%",
          "dps": "99.47",
          "dps-*": "99",
          "DPS": "99",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "99",
          "encdps": "96.86",
          "encdps-*": "96",
          "ENCDPS": "97",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "96",
          "hits": "63",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "4",
          "swings": "67",
          "tohit": "94.03",
          "TOHIT": "94",
          "maxhit": "乱れ雪月花-3727",
          "MAXHIT": "3727",
          "maxhit-*": "乱れ雪月花-3.73K",
          "MAXHIT-*": "3727",
          "healed": "90918",
          "healed%": "4%",
          "enchps": "104.03",
          "enchps-*": "104",
          "ENCHPS": "104",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "104",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "26",
          "cures": "0",
          "maxheal": "Unknown-5101",
          "MAXHEAL": "5101",
          "maxhealward": "Unknown-5101",
          "MAXHEALWARD": "5101",
          "maxheal-*": "Unknown-5.10K",
          "MAXHEAL-*": "5.10K",
          "maxhealward-*": "Unknown-5.10K",
          "MAXHEALWARD-*": "5.10K",
          "damagetaken": "156406",
          "damagetaken-*": "156.41K",
          "healstaken": "99401",
          "healstaken-*": "99.40K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "6",
          "deaths": "1",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "63",
          "Last60DPS": "62",
          "Job": "Sam",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "83.33",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "90918"
        },
        "Carl Tanner": {
          "n": "\n",
          "t": "\t",
          "name": "Carl Tanner",
          "duration": "02:10",
          "DURATION": "130",
          "damage": "71955",
          "damage-m": "0.07",
          "damage-b": "0.00",
          "damage-*": "71.96K",
          "DAMAGE-k": "72",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "71K",
          "damage%": "1%",
          "dps": "553.50",
          "dps-*": "553",
          "DPS": "554",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "553",
          "encdps": "82.33",
          "encdps-*": "82",
          "ENCDPS": "82",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "82",
          "hits": "9",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "9",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "レーザーエックススウォード-12499",
          "MAXHIT": "12499",
          "maxhit-*": "レーザーエックススウォード-12.50K",
          "MAXHIT-*": "12K",
          "healed": "0",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "0.00",
          "enchps-*": "0",
          "ENCHPS": "0",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "0",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "0",
          "cures": "0",
          "maxheal": "",
          "MAXHEAL": "",
          "maxhealward": "",
          "MAXHEALWARD": "",
          "maxheal-*": "",
          "MAXHEAL-*": "",
          "maxhealward-*": "",
          "MAXHEALWARD-*": "",
          "damagetaken": "110678",
          "damagetaken-*": "110.68K",
          "healstaken": "0",
          "healstaken-*": "0",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "2",
          "deaths": "2",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Nin",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "0"
        },
        "Angel Twist": {
          "n": "\n",
          "t": "\t",
          "name": "Angel Twist",
          "duration": "14:07",
          "DURATION": "847",
          "damage": "65549",
          "damage-m": "0.07",
          "damage-b": "0.00",
          "damage-*": "65.55K",
          "DAMAGE-k": "66",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "65K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "77.39",
          "dps-*": "77",
          "DPS": "77",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "77",
          "encdps": "75.00",
          "encdps-*": "74",
          "ENCDPS": "75",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "74",
          "hits": "33",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "33",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "返し雪月花-4400",
          "MAXHIT": "4400",
          "maxhit-*": "返し雪月花-4.40K",
          "MAXHIT-*": "4400",
          "healed": "28600",
          "healed%": "1%",
          "enchps": "32.72",
          "enchps-*": "32",
          "ENCHPS": "33",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "32",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "9",
          "cures": "0",
          "maxheal": "Unknown-4948",
          "MAXHEAL": "4948",
          "maxhealward": "Unknown-4948",
          "MAXHEALWARD": "4948",
          "maxheal-*": "Unknown-4.95K",
          "MAXHEAL-*": "4.95K",
          "maxhealward-*": "Unknown-4.95K",
          "MAXHEALWARD-*": "4.95K",
          "damagetaken": "19370",
          "damagetaken-*": "19.37K",
          "healstaken": "31347",
          "healstaken-*": "31.35K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "1",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "88",
          "Last60DPS": "254",
          "Job": "Sam",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "28600"
        },
        "Carmel Tae-yeon": {
          "n": "\n",
          "t": "\t",
          "name": "Carmel Tae-yeon",
          "duration": "13:19",
          "DURATION": "799",
          "damage": "51555",
          "damage-m": "0.05",
          "damage-b": "0.00",
          "damage-*": "51.56K",
          "DAMAGE-k": "52",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "51K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "64.52",
          "dps-*": "64",
          "DPS": "65",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "64",
          "encdps": "58.99",
          "encdps-*": "58",
          "ENCDPS": "59",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "58",
          "hits": "41",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "7",
          "swings": "48",
          "tohit": "85.42",
          "TOHIT": "85",
          "maxhit": "ハート・オブ・ミゼリ-4029",
          "MAXHIT": "4029",
          "maxhit-*": "ハート・オブ・ミゼリ-4.03K",
          "MAXHIT-*": "4029",
          "healed": "182408",
          "healed%": "9%",
          "enchps": "208.70",
          "enchps-*": "208",
          "ENCHPS": "209",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "208",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "41",
          "cures": "0",
          "maxheal": "Unknown-6631",
          "MAXHEAL": "6631",
          "maxhealward": "Unknown-6631",
          "MAXHEALWARD": "6631",
          "maxheal-*": "Unknown-6.63K",
          "MAXHEAL-*": "6.63K",
          "maxhealward-*": "Unknown-6.63K",
          "MAXHEALWARD-*": "6.63K",
          "damagetaken": "105762",
          "damagetaken-*": "105.76K",
          "healstaken": "228413",
          "healstaken-*": "228.41K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "2",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Whm",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "83.33",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "182408"
        },
        "Karl Touya": {
          "n": "\n",
          "t": "\t",
          "name": "Karl Touya",
          "duration": "13:04",
          "DURATION": "784",
          "damage": "42379",
          "damage-m": "0.04",
          "damage-b": "0.00",
          "damage-*": "42.38K",
          "DAMAGE-k": "42",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "42K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "54.05",
          "dps-*": "54",
          "DPS": "54",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "54",
          "encdps": "48.49",
          "encdps-*": "48",
          "ENCDPS": "48",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "48",
          "hits": "40",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "3",
          "swings": "43",
          "tohit": "93.02",
          "TOHIT": "93",
          "maxhit": "グレア-1779",
          "MAXHIT": "1779",
          "maxhit-*": "グレア-1.78K",
          "MAXHIT-*": "1779",
          "healed": "75594",
          "healed%": "4%",
          "enchps": "86.49",
          "enchps-*": "86",
          "ENCHPS": "86",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "86",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "20",
          "cures": "0",
          "maxheal": "Unknown-5551",
          "MAXHEAL": "5551",
          "maxhealward": "Unknown-5551",
          "MAXHEALWARD": "5551",
          "maxheal-*": "Unknown-5.55K",
          "MAXHEAL-*": "5.55K",
          "maxhealward-*": "Unknown-5.55K",
          "MAXHEALWARD-*": "5.55K",
          "damagetaken": "98323",
          "damagetaken-*": "98.32K",
          "healstaken": "80978",
          "healstaken-*": "80.98K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "1",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Whm",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "92.50",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "75594"
        },
        "Mendel Thornton": {
          "n": "\n",
          "t": "\t",
          "name": "Mendel Thornton",
          "duration": "13:30",
          "DURATION": "810",
          "damage": "41448",
          "damage-m": "0.04",
          "damage-b": "0.00",
          "damage-*": "41.45K",
          "DAMAGE-k": "41",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "41K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "51.17",
          "dps-*": "51",
          "DPS": "51",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "51",
          "encdps": "47.42",
          "encdps-*": "47",
          "ENCDPS": "47",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "47",
          "hits": "30",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "6",
          "swings": "36",
          "tohit": "83.33",
          "TOHIT": "83",
          "maxhit": "霊泉の炎-2636",
          "MAXHIT": "2636",
          "maxhit-*": "霊泉の炎-2.64K",
          "MAXHIT-*": "2636",
          "healed": "13118",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "15.01",
          "enchps-*": "15",
          "ENCHPS": "15",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "15",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "4",
          "cures": "0",
          "maxheal": "Unknown-5273",
          "MAXHEAL": "5273",
          "maxhealward": "Unknown-5273",
          "MAXHEALWARD": "5273",
          "maxheal-*": "Unknown-5.27K",
          "MAXHEAL-*": "5.27K",
          "maxhealward-*": "Unknown-5.27K",
          "MAXHEALWARD-*": "5.27K",
          "damagetaken": "11589",
          "damagetaken-*": "11.59K",
          "healstaken": "13118",
          "healstaken-*": "13.12K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "1",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "83",
          "Job": "Smn",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "40.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "13118"
        },
        "Saul Todman": {
          "n": "\n",
          "t": "\t",
          "name": "Saul Todman",
          "duration": "11:17",
          "DURATION": "677",
          "damage": "31228",
          "damage-m": "0.03",
          "damage-b": "0.00",
          "damage-*": "31.23K",
          "DAMAGE-k": "31",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "31K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "46.13",
          "dps-*": "46",
          "DPS": "46",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "46",
          "encdps": "35.73",
          "encdps-*": "35",
          "ENCDPS": "36",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "35",
          "hits": "24",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "24",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "ドリル-3627",
          "MAXHIT": "3627",
          "maxhit-*": "ドリル-3.63K",
          "MAXHIT-*": "3627",
          "healed": "5349",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "6.12",
          "enchps-*": "6",
          "ENCHPS": "6",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "6",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "1",
          "cures": "0",
          "maxheal": "Unknown-5349",
          "MAXHEAL": "5349",
          "maxhealward": "Unknown-5349",
          "MAXHEALWARD": "5349",
          "maxheal-*": "Unknown-5.35K",
          "MAXHEAL-*": "5.35K",
          "maxhealward-*": "Unknown-5.35K",
          "MAXHEALWARD-*": "5.35K",
          "damagetaken": "37411",
          "damagetaken-*": "37.41K",
          "healstaken": "5349",
          "healstaken-*": "5.35K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "1",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Mch",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "5349"
        },
        "Paul Talos": {
          "n": "\n",
          "t": "\t",
          "name": "Paul Talos",
          "duration": "07:52",
          "DURATION": "472",
          "damage": "26155",
          "damage-m": "0.03",
          "damage-b": "0.00",
          "damage-*": "26.16K",
          "DAMAGE-k": "26",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "26K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "55.41",
          "dps-*": "55",
          "DPS": "55",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "55",
          "encdps": "29.93",
          "encdps-*": "29",
          "ENCDPS": "30",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "29",
          "hits": "19",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "19",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "デスフレア-3373",
          "MAXHIT": "3373",
          "maxhit-*": "デスフレア-3.37K",
          "MAXHIT-*": "3373",
          "healed": "7880",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "9.02",
          "enchps-*": "9",
          "ENCHPS": "9",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "9",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "3",
          "cures": "0",
          "maxheal": "Unknown-4741",
          "MAXHEAL": "4741",
          "maxhealward": "Unknown-4741",
          "MAXHEALWARD": "4741",
          "maxheal-*": "Unknown-4.74K",
          "MAXHEAL-*": "4.74K",
          "maxhealward-*": "Unknown-4.74K",
          "MAXHEALWARD-*": "4.74K",
          "damagetaken": "789",
          "damagetaken-*": "789",
          "healstaken": "7880",
          "healstaken-*": "7.88K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Smn",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "7880"
        },
        "Nicolas Gutchi": {
          "n": "\n",
          "t": "\t",
          "name": "Nicolas Gutchi",
          "duration": "03:42",
          "DURATION": "222",
          "damage": "25701",
          "damage-m": "0.03",
          "damage-b": "0.00",
          "damage-*": "25.70K",
          "DAMAGE-k": "26",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "25K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "115.77",
          "dps-*": "115",
          "DPS": "116",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "115",
          "encdps": "29.41",
          "encdps-*": "29",
          "ENCDPS": "29",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "29",
          "hits": "6",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "6",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "ホークブラスター-6931",
          "MAXHIT": "6931",
          "maxhit-*": "ホークブラスター-6.93K",
          "MAXHIT-*": "6931",
          "healed": "0",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "0.00",
          "enchps-*": "0",
          "ENCHPS": "0",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "0",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "0",
          "cures": "0",
          "maxheal": "",
          "MAXHEAL": "",
          "maxhealward": "",
          "MAXHEALWARD": "",
          "maxheal-*": "",
          "MAXHEAL-*": "",
          "maxhealward-*": "",
          "MAXHEALWARD-*": "",
          "damagetaken": "0",
          "damagetaken-*": "0",
          "healstaken": "0",
          "healstaken-*": "0",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Gnb",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "---",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "0"
        },
        "Maxwell Tudor": {
          "n": "\n",
          "t": "\t",
          "name": "Maxwell Tudor",
          "duration": "13:47",
          "DURATION": "827",
          "damage": "22947",
          "damage-m": "0.02",
          "damage-b": "0.00",
          "damage-*": "22.95K",
          "DAMAGE-k": "23",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "22K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "27.75",
          "dps-*": "27",
          "DPS": "28",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "27",
          "encdps": "26.26",
          "encdps-*": "26",
          "ENCDPS": "26",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "26",
          "hits": "11",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "2",
          "swings": "13",
          "tohit": "84.62",
          "TOHIT": "85",
          "maxhit": "ハート・オブ・ミゼリ-4335",
          "MAXHIT": "4335",
          "maxhit-*": "ハート・オブ・ミゼリ-4.34K",
          "MAXHIT-*": "4335",
          "healed": "19825",
          "healed%": "1%",
          "enchps": "22.68",
          "enchps-*": "22",
          "ENCHPS": "23",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "22",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "8",
          "cures": "0",
          "maxheal": "Unknown-3015",
          "MAXHEAL": "3015",
          "maxhealward": "Unknown-3015",
          "MAXHEALWARD": "3015",
          "maxheal-*": "Unknown-3.02K",
          "MAXHEAL-*": "3.02K",
          "maxhealward-*": "Unknown-3.02K",
          "MAXHEALWARD-*": "3.02K",
          "damagetaken": "8291",
          "damagetaken-*": "8.29K",
          "healstaken": "25208",
          "healstaken-*": "25.21K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "17",
          "Job": "Whm",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "50.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "19825"
        },
        "Justice Suzuki": {
          "n": "\n",
          "t": "\t",
          "name": "Justice Suzuki",
          "duration": "09:37",
          "DURATION": "577",
          "damage": "15155",
          "damage-m": "0.02",
          "damage-b": "0.00",
          "damage-*": "15.16K",
          "DAMAGE-k": "15",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "15K",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "26.27",
          "dps-*": "26",
          "DPS": "26",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "26",
          "encdps": "17.34",
          "encdps-*": "17",
          "ENCDPS": "17",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "17",
          "hits": "11",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "0",
          "swings": "11",
          "tohit": "100.00",
          "TOHIT": "100",
          "maxhit": "蒸気噴射-2723",
          "MAXHIT": "2723",
          "maxhit-*": "蒸気噴射-2.72K",
          "MAXHIT-*": "2723",
          "healed": "0",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "0.00",
          "enchps-*": "0",
          "ENCHPS": "0",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "0",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "0",
          "cures": "0",
          "maxheal": "",
          "MAXHEAL": "",
          "maxhealward": "",
          "MAXHEALWARD": "",
          "maxheal-*": "",
          "MAXHEAL-*": "",
          "maxhealward-*": "",
          "MAXHEALWARD-*": "",
          "damagetaken": "450107",
          "damagetaken-*": "450.11K",
          "healstaken": "0",
          "healstaken-*": "0",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "5000",
          "powerheal-*": "5.00K",
          "kills": "0",
          "deaths": "4",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Drg",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "100.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "0"
        },
        "Abdul Trenton": {
          "n": "\n",
          "t": "\t",
          "name": "Abdul Trenton",
          "duration": "06:43",
          "DURATION": "403",
          "damage": "9121",
          "damage-m": "0.01",
          "damage-b": "0.00",
          "damage-*": "9.12K",
          "DAMAGE-k": "9",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "9121",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "22.63",
          "dps-*": "22",
          "DPS": "23",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "22",
          "encdps": "10.44",
          "encdps-*": "10",
          "ENCDPS": "10",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "10",
          "hits": "7",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "2",
          "swings": "9",
          "tohit": "77.78",
          "TOHIT": "78",
          "maxhit": "グレア-1691",
          "MAXHIT": "1691",
          "maxhit-*": "グレア-1.69K",
          "MAXHIT-*": "1691",
          "healed": "2506",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "2.87",
          "enchps-*": "2",
          "ENCHPS": "3",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "2",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "1",
          "cures": "0",
          "maxheal": "Unknown-2506",
          "MAXHEAL": "2506",
          "maxhealward": "Unknown-2506",
          "MAXHEALWARD": "2506",
          "maxheal-*": "Unknown-2.51K",
          "MAXHEAL-*": "2.51K",
          "maxhealward-*": "Unknown-2.51K",
          "MAXHEALWARD-*": "2.51K",
          "damagetaken": "0",
          "damagetaken-*": "0",
          "healstaken": "2506",
          "healstaken-*": "2.51K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Whm",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "0.00",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "2506"
        },
        "Joel Toussaint": {
          "n": "\n",
          "t": "\t",
          "name": "Joel Toussaint",
          "duration": "00:14",
          "DURATION": "14",
          "damage": "8193",
          "damage-m": "0.01",
          "damage-b": "0.00",
          "damage-*": "8.19K",
          "DAMAGE-k": "8",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "8193",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "585.21",
          "dps-*": "585",
          "DPS": "585",
          "DPS-k": "1",
          "DPS-m": "0",
          "DPS-*": "585",
          "encdps": "9.37",
          "encdps-*": "9",
          "ENCDPS": "9",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "9",
          "hits": "5",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "1",
          "swings": "6",
          "tohit": "83.33",
          "TOHIT": "83",
          "maxhit": "ハイジャンプ-2637",
          "MAXHIT": "2637",
          "maxhit-*": "ハイジャンプ-2.64K",
          "MAXHIT-*": "2637",
          "healed": "0",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "0.00",
          "enchps-*": "0",
          "ENCHPS": "0",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "0",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "0",
          "cures": "0",
          "maxheal": "",
          "MAXHEAL": "",
          "maxhealward": "",
          "MAXHEALWARD": "",
          "maxheal-*": "",
          "MAXHEAL-*": "",
          "maxhealward-*": "",
          "MAXHEALWARD-*": "",
          "damagetaken": "6021",
          "damagetaken-*": "6.02K",
          "healstaken": "966",
          "healstaken-*": "966",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Drg",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "83.33",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "0"
        },
        "Niall Talbot": {
          "n": "\n",
          "t": "\t",
          "name": "Niall Talbot",
          "duration": "00:30",
          "DURATION": "30",
          "damage": "2781",
          "damage-m": "0.00",
          "damage-b": "0.00",
          "damage-*": "2.78K",
          "DAMAGE-k": "3",
          "DAMAGE-m": "0",
          "DAMAGE-b": "0",
          "DAMAGE-*": "2781",
          "damage%": Math.floor(Math.random() * 51) + '%',
          "dps": "92.70",
          "dps-*": "92",
          "DPS": "93",
          "DPS-k": "0",
          "DPS-m": "0",
          "DPS-*": "92",
          "encdps": "3.18",
          "encdps-*": "3",
          "ENCDPS": "3",
          "ENCDPS-k": "0",
          "ENCDPS-m": "0",
          "ENCDPS-*": "3",
          "hits": "1",
          "crithits": "0",
          "crithit%": Math.floor(Math.random() * 51) + '%',
          "crittypes": "-",
          "misses": "0",
          "hitfailed": "2",
          "swings": "3",
          "tohit": "33.33",
          "TOHIT": "33",
          "maxhit": "乱れ雪月花-2781",
          "MAXHIT": "2781",
          "maxhit-*": "乱れ雪月花-2.78K",
          "MAXHIT-*": "2781",
          "healed": "6894",
          "healed%": Math.floor(Math.random() * 51) + '%',
          "enchps": "7.89",
          "enchps-*": "7",
          "ENCHPS": "8",
          "ENCHPS-k": "0",
          "ENCHPS-m": "0",
          "ENCHPS-*": "7",
          "critheals": "0",
          "critheal%": Math.floor(Math.random() * 51) + '%',
          "heals": "2",
          "cures": "0",
          "maxheal": "Unknown-4946",
          "MAXHEAL": "4946",
          "maxhealward": "Unknown-4946",
          "MAXHEALWARD": "4946",
          "maxheal-*": "Unknown-4.95K",
          "MAXHEAL-*": "4.95K",
          "maxhealward-*": "Unknown-4.95K",
          "MAXHEALWARD-*": "4.95K",
          "damagetaken": "5372",
          "damagetaken-*": "5.37K",
          "healstaken": "8093",
          "healstaken-*": "8.09K",
          "powerdrain": "0",
          "powerdrain-*": "0",
          "powerheal": "0",
          "powerheal-*": "0",
          "kills": "0",
          "deaths": "0",
          "threatstr": "+(0)0/-(0)0",
          "threatdelta": "0",
          "Last10DPS": "0",
          "Last30DPS": "0",
          "Last60DPS": "0",
          "Job": "Sam",
          "ParryPct": Math.floor(Math.random() * 51) + '%',
          "BlockPct": Math.floor(Math.random() * 51) + '%',
          "IncToHit": "66.67",
          "OverHealPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitPct": Math.floor(Math.random() * 51) + '%',
          "DirectHitCount": "0",
          "CritDirectHitCount": "0",
          "CritDirectHitPct": Math.floor(Math.random() * 51) + '%',
          "overHeal": "0",
          "damageShield": "0",
          "absorbHeal": "6894"
        }
      },
      "isActive": "false"
    };
    return json;
  }